bhyve_email: dummy@test.com
bhyve_password: dummy
blink_email: dummy@test.com
blink_password: dummy
cameras: []
device_id: dummy
duration_seconds: 3
poll_interval_seconds: 30
render_api_key: ''
zone_number: 6

