blink_email: "ajusunaina@gmail.com"
blink_password: "3002Sharm@1"
camera_name: "Patio"

bhyve_email: "ajusunaina@gmail.com"
bhyve_password: "Sharmjug@1"
device_id: "607220244f0c161d5a0d1648"
zone_number: 6
duration_seconds: 20

poll_interval_seconds: 60